### ISSUE TITLE
Mudar o comportamento padrão em caso de detecção de acesso root

### ISSUE THREAD

**Issue by Kartatz** [adonaipinheiro/TabNews#10]
Seguindo a discussão que tivemos na #9, reafirmo aqui minha sugestão:

Considere implementar um meio de deixar o usuário ciente de que o seu uso ao aplicativo foi restringido pois foi detectado que o dispositivo usado possui o bootloader desbloqueado.

O comportamento atual faz com que o aplicativo feche abruptamente sem dar detalhes, o qual pode dar a falsa impressão de que o aplicativo apresentou um mau funcionamento (crash).

**Comment by adonaipinheiro** [comment]
@Kartatz , consultei uma empresa de Cyber Security e me aconselharam a não dar nenhum aviso ou tempo para o fechamento da APP. Manterei o comportamento atual.

**Comment by Kartatz** [comment]
Achei que o aplicativo era seu, mas aparentemente você depende da opinião de terceiros para gerenciá-lo. É uma pena.

Ainda assim, não entendo a motivação para isso. Até mesmo o aplicativo do Google Pay exibe um aviso explicitamente citando o root como causa em caso de detecção, e ele obviamente não fecha de imediato. Confirme na imagem abaixo:

![screenshot.jpg](https://github.com/adonaipinheiro/TabNews/assets/105828205/e609aa43-8614-4141-8494-23b2028b9c16)

Essa tal "empresa de Cyber Security" usa práticas de segurança que nem mesmo o Google usa. A eficácia delas é no mínimo questionável.

**Comment by adonaipinheiro** [comment]
@Kartatz atenderei sua issue. Vou exibir uma mensagem, porém continuará não conseguindo utilizar a aplicação.

**Comment by Kartatz** [comment]
Grato por isso.

Não possuo opiniões especificas sobre o design, então você pode fazê-lo como achar mais razoável.

O ponto principal é passar o aviso de forma clara.
